[[overrides]]
path = "tools/node"
from = "bafkreidhwdqb3p6lqzxe55na5hrdrw7d5meput4mpfcixcspo2nevbbafi"

[[overrides]]
path = "tools/prettier"
from = "bafkreiehxpsmilwpzvvv7sa6noo3wnr3tz3jckg4ggv2krtz3eywosr5ni"
